server:
  context-path: /cities
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5532/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:8761/eureka